[messages]
[messages.one_liners]
# Add those cheeky or shitty one liners here. 
# Command name = Oneliner enna format
pai = "Hai Friends üëã"
kween = "‡¥Ö‡¥≤‡¥µ‡¥≤‡¥æ‡¥§‡¥ø"
abru = "‡¥û‡¥æ‡µª ‡¥®‡¥®‡µç‡¥®‡¥æ‡¥Ø‡¥ø guis"
githuboli = "‡¥é‡¥®‡µç‡¥®‡¥æ ‡¥â‡¥£‡µç"
subin = "‡¥é‡¥®‡µç‡¥§‡¥æ‡¥ü‡¥æ ‡¥Æ‡µà‡¥∞‡µá"
ayin = "Ayin poyi oomfanam mister"
pewer = "‚ö°Ô∏è"
s = "Athu Sarcasm aarunnu ketto"
pp = "Hehe"
beepathu = 'phaa kelava'


[messages.reply_only_one_liners]
# Same but for replies and Subin calling everyone else a myren
qt = "**Condom** related ‡¥ï‡¥æ‡¥∞‡µç‡¥Ø‡¥ô‡µç‡¥ô‡µæ‡¥ï‡µç‡¥ï‡µÅ SPAthan ‡¥é‡¥®‡µç‡¥® ‡¥∏‡µç‡¥µ‡¥Ø‡¥Ç‡¥™‡µç‡¥∞‡¥ñ‡µç‡¥Ø‡¥æ‡¥™‡¥ø‡¥§ \n **Condom Boi (@thetronjohnson)** ne vilikkuka"
tq = "‡¥®‡¥®‡µç‡¥¶‡¥ø ‡¥â‡¥£‡µç‡¥ü‡µç ‡¥Æ‡µà‡¥∞‡µá...üòç You're Awesome ‚ù§Ô∏è"
lol = "‡¥é‡¥ü‡¥æ mwonuse ‡¥Ö‡¥§‡µç ‡¥ï‡¥ø‡¥ü‡µÅ ‡¥µ‡¥ø‡¥±‡µç‡¥±‡¥æ‡¥∞‡µÅ‡¥®‡µç‡¥®‡µÅ ‡¥ï‡µá‡¥ü‡µç‡¥ü‡µã. ‡¥ï‡¥ø‡¥≤‡µç‡¥≤‡¥æ‡¥ü‡¥ø ‡¥§‡¥®‡µç‡¥®‡µÜ\npoli...\nkidu...\n‡¥Æ‡µç‡¥Ø‡¥æ‡¥∞‡¥ï‡¥Ç ‡¥§‡¥®‡µç‡¥®‡µÜ"

[messages.stickers]
# Parayendallo, stickers varanamenkil enik sticker ayachthannam 
gawd = "stickers/levi.webp"

[messages.messages_with_stickers]
# The OG GKR stuff with that wonderful chiri
gkr = ["‡¥é‡¥≤‡µç‡¥≤‡¥æ‡¥µ‡¥ø‡¥ß Premium Accountukalkum GKR'ne ‡¥∏‡¥Æ‡µÄ‡¥™‡¥ø‡¥ï‡µç‡¥ï‡µÅ‡¥ï", "stickers/gkr.webp"]

[messages.audio]
# Audio Files inte path
wow = "audio/wow.mp3"
dharwish = "audio/dharwish.mp3"
billy = "audio/billy-mon.mp3"
elixir = "audio/elixir.mpeg"

[constant]
help = """
Ammavan is here to help my pillers. Commands chuvade kodukkunnu

- /re - for re vilikkaling. Aareya re vilikkunnath enn koodi parayanam ketto
- /pai - for invoking Pai's signature message
- /kween - for replying to a message in kween's own language
- /abru - He's a good boi now
- /githuboli - IDK who put this shit here
- /gkr - Premium uyir bakkiyellam mayir. GKR inte sticker free aane
- /qt - You have called upon the catastrophic don, Kadayadi Baby err Quantum Kiran
- /gawd - I see no other gawd other than me memefied 
- /wow - Eda kunje adipoli
- /hbd - cliche bday wishes aan ente main
- /tq - nanni maathram ‚ù§Ô∏èüòò
- /pewer - Pewer varatte 
- /ayn - Ayin nammal ippo entha cheyya
- /s - Ath oru vittarunnu ketto
- /subin - Kunnamkulam king ningale avisambodhana cheyyunath aayirikkum
- /pp - The way MG Sreekumar Laughs
- /lol - Kidu vittaanallo mwonuse
- /dharwish - Depression veno ninakk?
- /billy - Eternal Laughter of the Billymon Mind
- /elixir - Nee Ethavanaada...?
- Hai paranjal siddhu varum üôà

Chilath okke reply il work cheyyunnath aan, ethaanenn enik ormayilla"""
